import fs from "node:fs";
import path from "node:path";

/**
 * Ensures that preview bundler runs have a dedicated env toggle so downstream
 * tooling can rely on a consistent flag without manual exports.
 *
 * Usage:
 *   pnpm exec tsx scripts/bundlers/ensure-preview-flag.ts vite:dev
 *   pnpm exec tsx scripts/bundlers/ensure-preview-flag.ts rspack:test
 */
function main(): void {
	const bundlerTarget = process.argv[2] ?? "rspack:test";

	const projectRoot = path.resolve(__dirname, "../../");
	const previewEnvPath = path.join(projectRoot, ".env.preview.local");

	const envMap = readEnvFile(previewEnvPath);

	if (!envMap.has("NEXT_PUBLIC_ENV")) {
		envMap.set("NEXT_PUBLIC_ENV", "preview");
	}

	envMap.set("NEXT_PUBLIC_PREVIEW_BUNDLER", bundlerTarget);
	envMap.set("NEXT_PUBLIC_PREVIEW_LAST_RUN", new Date().toISOString());

	writeEnvFile(previewEnvPath, envMap);

	console.info(
		`[preview] Ensured preview flags for "${bundlerTarget}" (${previewEnvPath}).`,
	);
}

function readEnvFile(filePath: string): Map<string, string> {
	if (!fs.existsSync(filePath)) {
		return new Map();
	}

	const contents = fs.readFileSync(filePath, "utf8");
	const map = new Map<string, string>();

	for (const line of contents.split(/\r?\n/u)) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith("#")) {
			continue;
		}

		const [rawKey, ...rawValueParts] = trimmed.split("=");
		const key = rawKey?.trim();
		if (!key) {
			continue;
		}

		const value = rawValueParts.join("=").trim();
		map.set(key, value);
	}

	return map;
}

function writeEnvFile(filePath: string, envMap: Map<string, string>): void {
	const header = [
		"# Auto-generated by scripts/bundlers/ensure-preview-flag.ts",
		"# Delete this file if you want to fully reset preview overrides.",
	];

	const body = [...envMap.entries()].map(([key, value]) => `${key}=${value}`);

	fs.writeFileSync(filePath, `${header.join("\n")}\n${body.join("\n")}\n`, {
		encoding: "utf8",
	});
}

main();
